platform :ios, '7.0'

pod 'Realm', '0.92.3'
pod 'AFNetworking', '2.5.3'
pod 'SVProgressHUD', '1.1.3'
pod 'SAMGradientView', '0.2.1'
pod 'UIImage+ImageWithColor', '1.2'
pod 'MTDates', '1.0.2'
pod 'SVProgressHUD', '1.1.3'
pod 'LUKeychainAccess', '~> 1.2.4'
pod 'GCNetworkReachability', '~> 1.3.2'
